default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gaultmillau_eu_development

test:
  <<: *default
  database: gaultmillau_eu_test

staging:
  <<: *default
  database: gaultmillau_eu_staging
  username: gaultmillau_eu
  password: <%= ENV['APPSOLUTE_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: gaultmillau_eu_production
  username: gaultmillau_eu
  password: <%= ENV['APPSOLUTE_DATABASE_PASSWORD'] %>
