default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: culinary_guide_development

test:
  <<: *default
  database: culinary_guide_test

staging:
  <<: *default
  database: culinary_guide_staging
  username: culinary_guide
  password: <%= ENV['CULINARY_GUIDE_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: culinary_guide_production
  username: culinary_guide
  password: <%= ENV['CULINARY_GUIDE_DATABASE_PASSWORD'] %>
