default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: culinary_guide_api_development

test:
  <<: *default
  database: culinary_guide_api_test

staging:
  <<: *default
  database: culinary_guide_api_staging
  username: culinary_guide_api
  password: <%= ENV['CULINARY_GUIDE_API_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: culinary_guide_api_production
  username: culinary_guide_api
  password: <%= ENV['CULINARY_GUIDE_API_DATABASE_PASSWORD'] %>
